name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
      - run: docker build -t ziuuk/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true ziuuk/react-test npm test

      - run: docker build -t ziuuk/multi-client-up ./client
      - run: docker build -t ziuuk/multi-nginx-up ./nginx
      - run: docker build -t ziuuk/multi-server-up ./server
      - run: docker build -t ziuuk/multi-worker-up ./worker

      - run: docker push ziuuk/multi-client-up
      - run: docker push ziuuk/multi-nginx-up
      - run: docker push ziuuk/multi-server-up
      - run: docker push ziuuk/multi-worker-up

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

    #   - name: Deploy to EB
    #     uses: einaregilsson/beanstalk-deploy@v22
    #     with:
    #       aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
    #       aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
    #       application_name: multi-gh
    #       environment_name: Multigh-env
    #       existing_bucket_name: elasticbeanstalk-us-east-1-923445559289
    #       region: us-east-1
    #       version_label: ${{ github.sha }}
    #       deployment_package: deploy.zip
